# Generated by Django 5.1.7 on 2025-03-29 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('drug_id', models.AutoField(primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=255)),
                ('drug_type', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('dosage_form', models.CharField(blank=True, max_length=255, null=True)),
                ('strength', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('interactions', models.TextField(blank=True, null=True)),
                ('contraindications', models.TextField(blank=True, null=True)),
                ('side_effects', models.TextField(blank=True, null=True)),
                ('warnings', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('insurance_id', models.AutoField(primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=255)),
                ('policy_number', models.CharField(max_length=255, unique=True)),
                ('treatment_coverage_details', models.TextField()),
                ('amount_covered', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('demographic_details', models.CharField(max_length=255)),
                ('insurance_info', models.CharField(max_length=255)),
                ('emergency_contact', models.CharField(max_length=10)),
                ('ehr_link', models.CharField(max_length=255)),
                ('feedback_rating', models.PositiveSmallIntegerField()),
                ('registration_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffDetails',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('speciality', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('billing_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Denied', 'Denied')], default='Pending', max_length=10)),
                ('billing_date', models.DateField()),
                ('insurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.insurance')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientContact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=255)),
                ('address', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clinic.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('diagnoses', models.CharField(blank=True, max_length=255, null=True)),
                ('treatments', models.CharField(blank=True, max_length=255, null=True)),
                ('allergies', models.CharField(blank=True, max_length=255, null=True)),
                ('laboratory_test_results', models.TextField(blank=True, null=True)),
                ('imaging_studies', models.TextField(blank=True, null=True)),
                ('dosage_instruction', models.TextField(blank=True, null=True)),
                ('refill_requests', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('alert', models.TextField(default='No alert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patient')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.staffdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.billing')),
                ('insurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.insurance')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patient')),
            ],
        ),
        migrations.CreateModel(
            name='StaffContact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=255)),
                ('address', models.TextField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clinic.staffdetails')),
            ],
        ),
        migrations.CreateModel(
            name='PatientsAssigned',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patient')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.staffdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('appointment_status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('No-show', 'No-show')], default='Scheduled', max_length=10)),
                ('reschedule_count', models.IntegerField(default=0)),
                ('booking_method', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Mobile App', 'Mobile App')], default='Online', max_length=10)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reason_for_visit', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.patient')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.staffdetails')),
            ],
        ),
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_details', models.CharField(max_length=500)),
                ('severity_level', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], max_length=10)),
                ('alert', models.TextField()),
                ('drug_id_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug1', to='clinic.drug')),
                ('drug_id_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug2', to='clinic.drug')),
            ],
            options={
                'unique_together': {('drug_id_1', 'drug_id_2')},
            },
        ),
        migrations.CreateModel(
            name='PrescriptionDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('instructions', models.TextField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.drug')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.prescription')),
            ],
            options={
                'unique_together': {('prescription', 'drug')},
            },
        ),
    ]
