# Generated by Django 5.1.7 on 2025-04-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='alert',
            field=models.TextField(blank=True, default='No alert'),
        ),
    ]
